apiVersion: v1
kind: Service
metadata:
  name: reverse-proxy
  labels:
    run: reverse-proxy
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    run: reverse-proxy
